/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alura.hotelAlura.views;

import java.awt.Color;

/**
 *
 * @author CRISTIAN
 */
public class Principal extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        InitStyles();
    }

    public void InitStyles() {
        txt_titulo.putClientProperty("FlatLaf.style", "font: 32 $bold.font");
        txt_titulo.setForeground(new Color(13, 71, 161));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_principal = new javax.swing.JPanel();
        img_fondo = new javax.swing.JLabel();
        txt_titulo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 255, 0));
        setPreferredSize(new java.awt.Dimension(742, 398));

        bg_principal.setBackground(new java.awt.Color(255, 255, 255));

        img_fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\CRISTIAN\\Documents\\NetBeansProjects\\hotelAlura\\src\\main\\Resources\\hotel.png")); // NOI18N

        txt_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_titulo.setText("Relajate y renueva tu energía en el hotel alura.");

        javax.swing.GroupLayout bg_principalLayout = new javax.swing.GroupLayout(bg_principal);
        bg_principal.setLayout(bg_principalLayout);
        bg_principalLayout.setHorizontalGroup(
            bg_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_principalLayout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(img_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bg_principalLayout.setVerticalGroup(
            bg_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_principalLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(txt_titulo)
                .addGap(18, 18, 18)
                .addComponent(img_fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 316, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg_principal;
    private javax.swing.JLabel img_fondo;
    private javax.swing.JLabel txt_titulo;
    // End of variables declaration//GEN-END:variables
}
